export const GREETINGS = [
  "How's your day going?",
  "Ready to crush it?",
  "Hope you're having a great day!",
  "Let's make today count.",
  "You're doing great!",
  "Keep up the good work.",
  "Stay productive!",
  "Time to shine.",
  "What's the goal for today?",
  "Don't forget to take a break.",
  "Believe in yourself.",
  "Success is loading...",
  "Make it happen.",
  "You got this!",
  "Stay focused.",
  "Dream big, work hard.",
  "Sending positive vibes.",
  "Let's get things done.",
  "Today is a new opportunity.",
  "Focus on the good.",
  "Keep pushing forward.",
  "Your potential is endless.",
  "Work hard, stay humble.",
  "Turning dreams into plans.",
  "Consistency is key.",
  "Small steps, big progress.",
  "Enjoy the process.",
  "Stay hungry, stay foolish.",
  "Make today amazing.",
  "Productivity mode: ON.",
  "Let's win today.",
  "Mindset is everything.",
  "Create your own sunshine.",
  "Be the energy you want to attract.",
  "Happiness looks good on you.",
  "Stay positive.",
  "Work smart.",
  "Unlock your potential.",
  "Great things take time.",
  "Keep the momentum going.",
  "Just keep swimming.",
  "Every day is a fresh start.",
  "Do it with passion.",
  "Strive for progress.",
  "Be improved, not perfect.",
  "Limitless possibilities.",
  "Own the day.",
  "Turn ideas into reality.",
  "Stay inspired.",
  "Focus on what matters.",
  "Let's build something great."
];