export const PROFESSIONAL_TITLES = [
  { label: 'None', value: '' },
  { label: 'Mr.', value: 'Mr.' },
  { label: 'Ms.', value: 'Ms.' },
  { label: 'Mrs.', value: 'Mrs.' },
  { label: 'Dr.', value: 'Dr.' },
  { label: 'Engr. (Engineer)', value: 'Engr.' },
  { label: 'Atty. (Attorney)', value: 'Atty.' },
  { label: 'Prof. (Professor)', value: 'Prof.' },
  { label: 'Arch. (Architect)', value: 'Arch.' },
  { label: 'Hon. (Honorable)', value: 'Hon.' },
  { label: 'Rev. (Reverend)', value: 'Rev.' },
  { label: 'Fr. (Father)', value: 'Fr.' },
  { label: 'Sr. (Sister)', value: 'Sr.' },
  { label: 'Capt. (Captain)', value: 'Capt.' },
  { label: 'Col. (Colonel)', value: 'Col.' },
  { label: 'Gen. (General)', value: 'Gen.' },
  { label: 'Ofc. (Officer)', value: 'Ofc.' },
];

export const PROFESSIONAL_SUFFIXES = [
  { label: 'None', value: '' },
  { label: 'PhD (Doctor of Philosophy)', value: 'PhD' },
  { label: 'MIT (Master of Information Technology)', value: 'MIT' },
  { label: 'MBA (Master of Business Administration)', value: 'MBA' },
  { label: 'MA (Master of Arts)', value: 'MA' },
  { label: 'MS (Master of Science)', value: 'MS' },
  { label: 'CPA (Certified Public Accountant)', value: 'CPA' },
  { label: 'RN (Registered Nurse)', value: 'RN' },
  { label: 'MD (Doctor of Medicine)', value: 'MD' },
  { label: 'JD (Juris Doctor)', value: 'JD' },
  { label: 'LPT (Licensed Professional Teacher)', value: 'LPT' },
  { label: 'RPh (Registered Pharmacist)', value: 'RPh' },
  { label: 'REE (Registered Electrical Engineer)', value: 'REE' },
  { label: 'RCE (Registered Civil Engineer)', value: 'RCE' },
  { label: 'RME (Registered Mechanical Engineer)', value: 'RME' },
  { label: 'Jr. (Junior)', value: 'Jr.' },
  { label: 'Sr. (Senior)', value: 'Sr.' },
  { label: 'II (The Second)', value: 'II' },
  { label: 'III (The Third)', value: 'III' },
  { label: 'IV (The Fourth)', value: 'IV' },
];